### PR TITLE
Separate invalidation and invalidee.

### LINKED ISSUE #76: Multiple grouping in a row breaks invalidation
If the invalidator from the first grouping goes to the different hash, compared with the invalidee, the invalidation-mechanism would be broken

### PR DESCRIPTION
**Pull request by marnikitta**
Fixes #76

### CODE REVIEW

File: core/src/main/java/com/spbsu/flamestream/core/data/meta/Meta.java [hunk 1]
```diff
@@ -1,47 +1,75 @@
...
+
   @Override
   public int compareTo(Meta that) {
     return NATURAL_ORDER.compare(this, that);
   }
 
+  public boolean isInvalidedBy(Meta that) {
+    return globalTime.equals(that.globalTime)
+            && Arrays.equals(childIds, that.childIds)
+            && trace == that.trace
```
Comment (mrMakaronka) [inline core/src/main/java/com/spbsu/flamestream/core/data/meta/Meta.java]: Not optimal order of comparisons
